// Generated by gencpp from file kucing/motor_joystick.msg
// DO NOT EDIT!


#ifndef KUCING_MESSAGE_MOTOR_JOYSTICK_H
#define KUCING_MESSAGE_MOTOR_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kucing
{
template <class ContainerAllocator>
struct motor_joystick_
{
  typedef motor_joystick_<ContainerAllocator> Type;

  motor_joystick_()
    : steering(0)
    , throttle(0)  {
    }
  motor_joystick_(const ContainerAllocator& _alloc)
    : steering(0)
    , throttle(0)  {
  (void)_alloc;
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _throttle_type;
  _throttle_type throttle;





  typedef boost::shared_ptr< ::kucing::motor_joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kucing::motor_joystick_<ContainerAllocator> const> ConstPtr;

}; // struct motor_joystick_

typedef ::kucing::motor_joystick_<std::allocator<void> > motor_joystick;

typedef boost::shared_ptr< ::kucing::motor_joystick > motor_joystickPtr;
typedef boost::shared_ptr< ::kucing::motor_joystick const> motor_joystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kucing::motor_joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kucing::motor_joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kucing::motor_joystick_<ContainerAllocator1> & lhs, const ::kucing::motor_joystick_<ContainerAllocator2> & rhs)
{
  return lhs.steering == rhs.steering &&
    lhs.throttle == rhs.throttle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kucing::motor_joystick_<ContainerAllocator1> & lhs, const ::kucing::motor_joystick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kucing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kucing::motor_joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kucing::motor_joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kucing::motor_joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kucing::motor_joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kucing::motor_joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kucing::motor_joystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kucing::motor_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4dd5817de7802d91e66008f92eca79e";
  }

  static const char* value(const ::kucing::motor_joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4dd5817de7802d9ULL;
  static const uint64_t static_value2 = 0x1e66008f92eca79eULL;
};

template<class ContainerAllocator>
struct DataType< ::kucing::motor_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kucing/motor_joystick";
  }

  static const char* value(const ::kucing::motor_joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kucing::motor_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n"
"int16 throttle\n"
;
  }

  static const char* value(const ::kucing::motor_joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kucing::motor_joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kucing::motor_joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kucing::motor_joystick_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUCING_MESSAGE_MOTOR_JOYSTICK_H
